### ISSUE TITLE
Notices are not expiring properly

### ISSUE THREAD

**Issue by aaronware** [linchpin/courier#32]
Doesn't matter if you set an expiration, the notices are not expiring

**Comment by fischfood** [comment]
Update: Cron events are expiring, but the cron is set to run once an hour. I think the best route would be to have it run every 15 minutes. If we can force the cron to start at a set interval (:00, :15, ...) can we also set the time select to only allow selecting the 15 minute increments.

**Comment by aaronware** [comment]
This is all set for release/v1.0.5: I have this running every 5 minutes for expiring and purging.
