### ISSUE TITLE
Add Options for Visibility based on Post Type or ID

### ISSUE THREAD

**Issue by fischfood** [linchpin/courier#43]
If a notice is set to not be a Global Notice, show a few extra meta fields for:

Post Type: Pull a list of all post types in checkboxes, compare the get_post_type to the values set in that array

Post ID: A comma delimited input of page IDs. Reference if current page ID is in the array and show.

**Comment by aaronware** [comment]
The Global checkbox needs to be changed to a dropdown, with "Global" as the default option.
User Specific should still be available, as it already works.
Need to add new options within the dropdown for each public post type that is available.
Once a post type is picked. The admin will display if the notice should show for all posts within that post type, or if it should be specific.

See if there is a way to add "repeatable" field groups with out using something like CMB2

**Comment by aaronware** [comment]
This feature will not be implemented at this time. If we get to a point where this is a premium version. This will be one of the first features we will implement
