### ISSUE TITLE
If a Courier Notice is set to be a modal, force dismissible

### ISSUE THREAD

**Issue by fischfood** [linchpin/courier#44]
Currently, if a user sets a modal notice and doesn't check dismissible, the visitor has no way of closing the modal

**Comment by aaronware** [comment]
Wait isn't that how it should work? I mean it's not a great experience I guess but should that be something shown in the admin? Or should you not be allowed to say it's not dismissable?

**Comment by aaronware** [comment]
@fischfood ^

**Comment by aaronware** [comment]
Fixed in release/1.0.5
