### ISSUE TITLE
Disable Iris Color Picker Input unless editing a type in the design settings

### ISSUE THREAD

**Issue by aaronware** [linchpin/courier#49]
Currently the Iris plugin is initialized on the Courier Notice Type settings. You can click on it and it has a "select color" label. The current color should be displayed. But the color picking should only be initialized when the user actually edits a Type

**Comment by aaronware** [comment]
You pretty much have this done. Just assigning this over

**Comment by aaronware** [comment]
@maxinacube is this one technically done?

**Comment by maxinacube** [comment]
Need conditional on wpColorPicker initialization
