### ISSUE TITLE
Should have info above Copy Courier Shortcode

### ISSUE THREAD

**Issue by maxinacube** [linchpin/courier#53]
We should have info above Copy Courier Shortcode textarea explaining what the field is for

**Comment by aaronware** [comment]
Build it out as a built in wordpress notice that can be dismissed. Once dismissed it wont show up any more. This can be similar to what we've done in Mesh when it's a new user

**Comment by aaronware** [comment]
I added some information above the notices copy text. It needs to be able to actually be dismissed though
