### ISSUE TITLE
Notice Type and Icon Class should be independent

### ISSUE THREAD

**Issue by maxinacube** [linchpin/courier#54]
Not sure if these are actually tied together or if it's just a front-end display issue.

1. Edit a notice type in the admin
2. Change the name of the notice type and save
3. You'll see the notice icon name change to `icon-{notice-name}`
4. When editing the same notice type, the icon class will remain it's previous state

Upon further testing, I cannot update the icon-class at all

**Comment by aaronware** [comment]
@maxinacube this is pretty much done isn't it?
